# Generated by Django 5.2 on 2025-05-29 02:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0002_alter_subject_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject_code']},
        ),
        migrations.AddField(
            model_name='activity',
            name='date_assigned',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
