# Generated by Django 5.2 on 2025-05-29 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0003_alter_subject_options_activity_date_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_assigned',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
