# Generated by Django 5.2 on 2025-05-29 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0004_alter_activity_date_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMSapp.course'),
        ),
    ]
