# Generated by Django 5.2 on 2025-05-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0005_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='student_grade',
            field=models.CharField(default='Not graded yet', max_length=50),
        ),
    ]
