# Generated by Django 5.2 on 2025-05-30 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0006_alter_grade_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='student_grade',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
