# Generated by Django 5.2 on 2025-05-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0007_student_date_added_alter_grade_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_assigned',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='total_items',
            field=models.IntegerField(),
        ),
    ]
