# Generated by Django 5.2 on 2025-05-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0008_alter_activity_activity_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='date_assigned',
        ),
    ]
