# Generated by Django 5.2 on 2025-05-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0009_remove_activity_date_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='archived_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
