# Generated by Django 5.2 on 2025-05-31 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0011_subject_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_level', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')])),
                ('section_name', models.CharField(max_length=1)),
                ('max_students', models.IntegerField(default=40)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='SMSapp.course')),
            ],
            options={
                'ordering': ['course', 'year_level', 'section_name'],
                'unique_together': {('year_level', 'section_name', 'course')},
            },
        ),
    ]
