# Generated by Django 5.2 on 2025-05-31 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0012_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'year_level', 'section_name')},
        ),
        migrations.RemoveField(
            model_name='section',
            name='max_students',
        ),
    ]
