# Generated by Django 5.2 on 2025-05-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0013_alter_section_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('R', 'Regular'), ('I', 'Irregular')], default='R', max_length=1),
        ),
    ]
