# Generated by Django 5.2 on 2025-05-31 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0014_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='max_students',
            field=models.IntegerField(default=40),
        ),
    ]
